name: Secret Santa Image Build/Deploy

on:
  push:
    branches: [ master ]

jobs:
  build_container_image:
    runs-on: [ self-hosted, aws-ec2-private ]
    steps:
      - uses: actions/checkout@v2
      - run: ./jobs/build_container_image.sh 

  deploy_all_services:
    needs: build_container_image
    runs-on: [ self-hosted, aws-ec2-private ]
    steps:
      - uses: actions/checkout@v2
      - run: ./jobs/deploy_all_services.sh

  
