name: Secret Santa Test Suite

on:
  pull_request:
    branches: [ master ]

jobs:
  test_on_pull_request_to_master:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: ./test.sh